# Generated by Django 2.2.5 on 2020-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
